"""03d — LTE diagnostic V2 (deeper probe after 03c findings).

PURPOSE
  Test 03c surfaced:
    - INSTrument:CREate is unknown (-113) — no multi-app architecture
    - INSTrument:SELect rejects string args (-158) — accepts keyword/numeric only
    - All CONFigure:LTE:MEAS<n>: paths fail with -114 — measurement subtree
      not routed
    - SDK paths configure.multiEval.set_dmode etc. don't exist

  03d goes deeper:
    PHASE 1: Probe INSTrument:SELect with unquoted keywords + INSTrument:NSELect
    PHASE 2: Iterate INSTrument:NSELect 1..6, capture each resulting INSTrument:SELect?
    PHASE 3: Probe GPRF measurement subsystem (universal CMW100 baseline)
    PHASE 4: Probe LTE:SIGNaling tree (in case KM500 is signaling-based)
    PHASE 5: Exhaustively dump the LteMeas SDK attribute tree (3 levels deep)
    PHASE 6: Capture SCPI generated by known-good SDK calls

  No assertions — always passes. Paste the SUMMARY block when reporting.

PRE-RUN ENGINEER CHECK (manual)
  Before running this test, on the CMW100 front panel / touchscreen:
    1. Verify an LTE Meas application is loaded (typically under
       "Applications" → "Measurement" → "LTE Measurement Application")
    2. If listed but not active, click to START it
    3. Note which application name appears as "active" or "selected"

  Without this, no SCPI for LTE will work no matter what we try in code.

USAGE
  uv run pytest tests/bench_bringup/test_03d_cmw100_lte_diagnostics_v2.py \
      --openflow-config=tests/configs/u300b0_evt.yaml \
      --openflow-report=reports/03d-lte-diag-v2.json \
      --log-cli-level=INFO -v
"""
from __future__ import annotations

import logging

import pytest

logger = logging.getLogger(__name__)


def _query(cmw100, scpi: str) -> str:
    try:
        val = cmw100.cmwa.Base.utilities.query_str(scpi)
        logger.info("Q  %-60s -> %s", scpi, val)
        return val
    except Exception as exc:
        msg = f"<query failed: {exc}>"
        logger.info("Q  %-60s -> %s", scpi, msg)
        try:
            cmw100.cmwa.Base.utilities.write_str("*CLS")
        except Exception:
            pass
        return msg


def _write(cmw100, scpi: str) -> str:
    try:
        cmw100.cmwa.Base.utilities.write_str(scpi)
        logger.info("W  %-60s -> OK", scpi)
        return "OK"
    except Exception as exc:
        msg = f"<write failed: {exc}>"
        logger.info("W  %-60s -> %s", scpi, msg)
        try:
            cmw100.cmwa.Base.utilities.write_str("*CLS")
        except Exception:
            pass
        return msg


def _dump_attrs(obj, prefix: str = "", depth: int = 0, max_depth: int = 3,
                seen: set | None = None) -> list[tuple[str, str]]:
    """Recursively dump public attributes of an SDK object. Stops at
    max_depth and skips callables that look like SCPI command methods
    (we want the attribute tree, not the leaf operations)."""
    if seen is None:
        seen = set()
    if depth >= max_depth or id(obj) in seen:
        return []
    seen.add(id(obj))

    rows: list[tuple[str, str]] = []
    try:
        attrs = sorted(a for a in dir(obj)
                       if not a.startswith("_") and a not in {"close", "open"})
    except Exception:
        return rows

    for name in attrs:
        full_path = f"{prefix}.{name}" if prefix else name
        try:
            value = getattr(obj, name)
        except Exception as exc:
            rows.append((full_path, f"<getattr failed: {exc}>"))
            continue
        type_name = type(value).__name__
        rows.append((full_path, type_name))
        # Recurse into objects that look like SDK sub-trees (their class
        # name typically ends in `Cls` for rscmw-* SDKs).
        if type_name.endswith("Cls"):
            rows.extend(_dump_attrs(value, full_path, depth + 1, max_depth, seen))
    return rows


@pytest.mark.testcase("CMW100-LTE-DIAG-V2")
def test_cmw100_lte_diagnostics_v2(cmw100, results):
    """Deeper probe — focus on INSTrument:SELect / NSELect + SDK tree dump
    + GPRF + LTE:SIGNaling alternatives."""
    logger.info("=" * 70)
    logger.info("PHASE 0: baseline")
    logger.info("=" * 70)
    idn = _query(cmw100, "*IDN?")
    opt = _query(cmw100, "*OPT?")
    initial_app = _query(cmw100, "INSTrument:SELect?")
    initial_nselect = _query(cmw100, "INSTrument:NSELect?")

    # ----- PHASE 1: INSTrument:SELect unquoted + NSELect query -----------
    logger.info("=" * 70)
    logger.info("PHASE 1: INSTrument:SELect with unquoted keywords + NSELect")
    logger.info("=" * 70)
    select_keyword_attempts = [
        "INSTrument:SELect LTE",
        "INSTrument:SELect LTEMeas",
        "INSTrument:SELect LTEFDD",
        "INSTrument:SELect LTETDD",
        "INSTrument:SELect MEAS",
        "INSTrument:SELect GPRF",
        "INSTrument:SELect 1",
        "INSTrument:SELect 2",
    ]
    select_results: list[tuple[str, str, str, str]] = []
    for cmd in select_keyword_attempts:
        result = _write(cmw100, cmd)
        post_select = _query(cmw100, "INSTrument:SELect?")
        post_nselect = _query(cmw100, "INSTrument:NSELect?")
        select_results.append((cmd, result, post_select, post_nselect))

    # ----- PHASE 2: iterate INSTrument:NSELect 1..6 ----------------------
    logger.info("=" * 70)
    logger.info("PHASE 2: iterate INSTrument:NSELect 1..6 to enumerate apps")
    logger.info("=" * 70)
    nselect_results: list[tuple[int, str, str, str]] = []
    for i in range(1, 7):
        cmd = f"INSTrument:NSELect {i}"
        result = _write(cmw100, cmd)
        post_select = _query(cmw100, "INSTrument:SELect?")
        post_nselect = _query(cmw100, "INSTrument:NSELect?")
        nselect_results.append((i, result, post_select, post_nselect))

    # ----- PHASE 3: GPRF measurement subsystem (universal baseline) ------
    logger.info("=" * 70)
    logger.info("PHASE 3: GPRF measurement subsystem (universal on CMW100)")
    logger.info("=" * 70)
    gprf_probes = [
        "CONFigure:GPRF:MEASurement1:RFSettings:FREQuency 2.65e9",
        "CONFigure:GPRF:MEASurement1:RFSettings:FREQuency?",
        "CONFigure:GPRF:MEASurement1:RFSettings:EATTenuation 0",
        "CONFigure:GPRF:MEAS1:RFSettings:FREQuency?",
        "CONFigure:GPRF:MEAS:RFSettings:FREQuency?",
        "CONFigure:GPRF:MEASurement1:POWer:RANGe?",
        "INITiate:GPRF:MEASurement1:POWer",
    ]
    gprf_results: list[tuple[str, str]] = []
    for cmd in gprf_probes:
        if cmd.endswith("?"):
            result = _query(cmw100, cmd)
        else:
            result = _write(cmw100, cmd)
        gprf_results.append((cmd, result))

    # ----- PHASE 4: LTE:SIGNaling tree (KM500 might be signaling-side) ---
    logger.info("=" * 70)
    logger.info("PHASE 4: LTE:SIGNaling tree (in case KM500 is signaling, not meas)")
    logger.info("=" * 70)
    signaling_probes = [
        "CONFigure:LTE:SIGNaling1:CARRier:BAND OB7",
        "CONFigure:LTE:SIGNaling1:CARRier:BAND?",
        "CONFigure:LTE:SIGNaling1:CARRier:DLFRequency 2.65e9",
        "CONFigure:LTE:SIGNaling:CARRier:BAND?",
        "ROUTe:LTE:SIGNaling1:SCENario:SALone R11",
    ]
    signaling_results: list[tuple[str, str]] = []
    for cmd in signaling_probes:
        if cmd.endswith("?"):
            result = _query(cmw100, cmd)
        else:
            result = _write(cmw100, cmd)
        signaling_results.append((cmd, result))

    # ----- PHASE 5: full LteMeas SDK attribute tree ----------------------
    logger.info("=" * 70)
    logger.info("PHASE 5: full RsCmwLteMeas SDK attribute tree (3 levels deep)")
    logger.info("=" * 70)
    sdk_tree: list[tuple[str, str]] = []
    try:
        lte_sdk = cmw100.cmwa.LteMeas
        if lte_sdk is None:
            sdk_tree.append(("(top)", "<None>"))
        else:
            sdk_tree = _dump_attrs(lte_sdk, max_depth=3)
    except Exception as exc:
        sdk_tree.append(("(top-level)", f"<error: {exc}>"))

    # Also dump GprfMeas SDK if available (might be the right tree for KM500).
    gprf_tree: list[tuple[str, str]] = []
    try:
        gprf_sdk = cmw100.cmwa.GprfMeas
        if gprf_sdk is None:
            gprf_tree.append(("(top)", "<None>"))
        else:
            gprf_tree = _dump_attrs(gprf_sdk, max_depth=2)
    except Exception:
        pass

    # ----- PHASE 6: capture SCPI generated by SDK calls ------------------
    # The KILLER probe: enable SDK SCPI logging, call a known-good SDK
    # method (configure.rfSettings.set_eattenuation — we verified it
    # exists in 03c), and capture the exact SCPI the SDK sends. Whatever
    # tree the SDK uses is the right tree for this firmware.
    logger.info("=" * 70)
    logger.info("PHASE 6: capture SCPI emitted by SDK calls (the breakthrough)")
    logger.info("=" * 70)
    sdk_scpi_captures: list[tuple[str, list[str]]] = []
    try:
        lte_sdk = cmw100.cmwa.LteMeas
        if lte_sdk is None:
            sdk_scpi_captures.append(("(SDK None)", ["LteMeas SDK not initialized"]))
        else:
            # Attach a StringIO buffer to the SDK's SCPI logger.
            import io
            log_buf = io.StringIO()
            try:
                lte_sdk.utilities.logger.set_logging_target(log_buf)
                lte_sdk.utilities.logger.mode = lte_sdk.utilities.logger.mode.__class__.On
            except Exception as exc:
                logger.info("Could not enable SDK logger via set_logging_target: %s", exc)
                # Fallback: try the simpler log_to_console toggle
                try:
                    lte_sdk.utilities.logger.log_to_console = True
                except Exception:
                    pass

            # List of SDK calls to probe. Each entry: (description, callable).
            # We use methods we VERIFIED exist in 03c phase 5.
            probes = [
                ("configure.rfSettings.set_eattenuation(0)",
                 lambda: lte_sdk.configure.rfSettings.set_eattenuation(0)),
            ]
            # Try a few more known SDK paths defensively.
            for path_str in ["configure.rfSettings", "configure.multiEval",
                             "configure", "route"]:
                obj = lte_sdk
                ok = True
                for part in path_str.split("."):
                    try:
                        obj = getattr(obj, part)
                    except AttributeError:
                        ok = False
                        break
                if ok:
                    # Try common setter prefixes.
                    for method_name in dir(obj):
                        if method_name.startswith("set_") and not method_name.startswith("_"):
                            full = f"{path_str}.{method_name}"
                            method = getattr(obj, method_name)
                            # Just CALL it with a plausible value to capture the SCPI.
                            # We don't care about return value or success.
                            def make_probe(m, n):
                                def probe():
                                    # Try common signatures
                                    try:
                                        m(0)  # int/float
                                    except TypeError:
                                        try:
                                            m(False)  # bool
                                        except TypeError:
                                            try:
                                                m("FDD")  # str/enum
                                            except Exception:
                                                pass
                                    except Exception:
                                        pass
                                return probe
                            probes.append((full + "(probe)", make_probe(method, full)))
                            if len(probes) > 12:
                                break
                if len(probes) > 12:
                    break

            for desc, fn in probes[:15]:  # cap at 15 to keep log readable
                buf_before = log_buf.getvalue()
                try:
                    fn()
                    err = "ok"
                except Exception as exc:
                    err = f"{exc}"
                buf_after = log_buf.getvalue()
                new_log = buf_after[len(buf_before):]
                # Extract SCPI commands from the log (lines containing semicolon-free SCPI).
                scpi_lines = [ln.strip() for ln in new_log.splitlines() if ln.strip()]
                sdk_scpi_captures.append((desc, [f"result={err}", *scpi_lines[-10:]]))
                # Clear instrument error queue between probes.
                try:
                    cmw100.cmwa.Base.utilities.write_str("*CLS")
                except Exception:
                    pass
    except Exception as exc:
        sdk_scpi_captures.append(("(top-level)", [f"error: {exc}"]))

    # ----- SUMMARY -------------------------------------------------------
    logger.info("=" * 70)
    logger.info("SUMMARY — paste this whole block when reporting")
    logger.info("=" * 70)
    logger.info("  IDN: %s", idn)
    logger.info("  *OPT?: %s", opt)
    logger.info("  Initial INSTrument:SELect?  = %s", initial_app)
    logger.info("  Initial INSTrument:NSELect? = %s", initial_nselect)
    logger.info("")
    logger.info("  PHASE 1 - INSTrument:SELect unquoted attempts:")
    for cmd, result, sel, nsel in select_results:
        logger.info("    %s", cmd)
        logger.info("       result=%s  SELect?=%s  NSELect?=%s", result, sel, nsel)
    logger.info("")
    logger.info("  PHASE 2 - INSTrument:NSELect 1..6 sweep:")
    for i, result, sel, nsel in nselect_results:
        logger.info("    NSELect %d", i)
        logger.info("       result=%s  SELect?=%s  NSELect?=%s", result, sel, nsel)
    logger.info("")
    logger.info("  PHASE 3 - GPRF measurement probes:")
    for cmd, result in gprf_results:
        logger.info("    %s", cmd)
        logger.info("       -> %s", result)
    logger.info("")
    logger.info("  PHASE 4 - LTE:SIGNaling probes:")
    for cmd, result in signaling_results:
        logger.info("    %s", cmd)
        logger.info("       -> %s", result)
    logger.info("")
    logger.info("  PHASE 5 - LteMeas SDK tree (top %d rows shown):", min(60, len(sdk_tree)))
    for path, type_name in sdk_tree[:60]:
        logger.info("    %-60s %s", path, type_name)
    if len(sdk_tree) > 60:
        logger.info("    ... (and %d more — see full dump in pytest report JSON)",
                    len(sdk_tree) - 60)
    if gprf_tree:
        logger.info("")
        logger.info("  PHASE 5b - GprfMeas SDK tree (top %d rows):",
                    min(40, len(gprf_tree)))
        for path, type_name in gprf_tree[:40]:
            logger.info("    %-60s %s", path, type_name)
    logger.info("")
    logger.info("  PHASE 6 - SDK call → SCPI capture (the breakthrough probe):")
    for desc, log_lines in sdk_scpi_captures:
        logger.info("    %s", desc)
        for line in log_lines:
            logger.info("       %s", line)
    logger.info("=" * 70)

    results.publish(
        idn=idn,
        opt=opt,
        initial_app=initial_app,
        initial_nselect=initial_nselect,
        select_results=[{"cmd": c, "result": r, "select": s, "nselect": n}
                        for c, r, s, n in select_results],
        nselect_sweep=[{"n": i, "result": r, "select": s, "nselect": n}
                       for i, r, s, n in nselect_results],
        gprf_results=[{"cmd": c, "result": r} for c, r in gprf_results],
        signaling_results=[{"cmd": c, "result": r} for c, r in signaling_results],
        lte_sdk_tree=[{"path": p, "type": t} for p, t in sdk_tree],
        gprf_sdk_tree=[{"path": p, "type": t} for p, t in gprf_tree],
        sdk_scpi_captures=[{"desc": d, "log": ls} for d, ls in sdk_scpi_captures],
    )
